//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int client_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string full_name
        {
            get
            {
                return $"{last_name} {first_name} {middle_name}";
            }
        }
        public string phone { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string passport_data { get; set; }
        public System.DateTime registration_date { get; set; }
        public string photo { get; set; }
        public string photoOptimized
        {
            get
            {
                if (this.photo != null)
                {
                    return "Resources/" + this.photo;
                } else
                {
                    return "Resources/user_default.png";
                }
            }
        }
    
        public virtual ICollection<Contracts> Contracts { get; set; }
    }
}
