//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int client_id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string full_name
        {
            get
            {
                return $"{last_name} {first_name} {middle_name}";
            }
        }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string passport_data { get; set; }
        public System.DateTime registration_date { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string birth_signup_date
        {
            get
            {
                if (this.birthday != null)
                {
                    return ((System.DateTime)this.birthday).ToShortDateString() + " | " + this.registration_date.ToShortDateString();
                } else
                {
                    return "Отсутствует | " + this.registration_date.ToShortDateString();
                }
            }
        }
        public string photo { get; set; }
        public string photoOptimized
        {
            get
            {
                if (this.photo != null)
                {
                    return "Resources/" + this.photo;
                } else
                {
                    return "Resources/user_default.png";
                }
            }
        }
        public string gender { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }

        public string contracts
        {
            get
            {
                string cons = "";

                if (this.Contracts.ToList().Count != 0)
                {
                    foreach (var contract in this.Contracts.ToList())
                    {
                        cons = cons + contract.contract_number + " ";
                    }
                }

                return cons;
            }
        }
    }
}
