//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public Contracts()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int contract_id { get; set; }
        public int client_id { get; set; }
        public int tariff_id { get; set; }
        public string contract_number { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public decimal monthly_payment { get; set; }
        public Nullable<int> days_remaining { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Tariffs Tariffs { get; set; }
    }
}
