//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UFANETEntities : DbContext
    {
        private static UFANETEntities _context;

        public static UFANETEntities GetContext()
        {
            if (_context == null)
            {
                _context = new UFANETEntities();
            }

            return _context;
        }

        public UFANETEntities()
            : base("name=UFANETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Tariffs> Tariffs { get; set; }
    }
}
