//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.Tariffs = new HashSet<Tariffs>();
        }
    
        public int service_id { get; set; }
        public string service_name { get; set; }
        public string service_type { get; set; }
        public string description { get; set; }
        public decimal base_price { get; set; }
        public bool is_active { get; set; }
    
        public virtual ICollection<Tariffs> Tariffs { get; set; }
    }
}
