//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baibakov4122UfanetCourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariffs
    {
        public Tariffs()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int tariff_id { get; set; }
        public int service_id { get; set; }
        public string tariff_name { get; set; }
        public Nullable<int> speed_mbps { get; set; }
        public Nullable<int> channel_count { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Services Services { get; set; }
    }
}
